<?php namespace Modules\Menus\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use DB;

class MenuLinksTableSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('menu_links')->truncate();

        $menu_links = [

            [
                'id' => '1',
                'slug' => '/',
                'uri' => '/',
                'title' => 'Home',
                'status' => '1',
                'tagline' => '',
                'parent_id' => null,
                'link_type' => '',
                'category_id' => null,
                'active' => '',
                'category_name' => '',
                'url' => '/',
                'menu_id' => '1',
                'position' => null,
                'target' => '',
                'restricted_to' => '',
                'class' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '2',
                'slug' => '/',
                'uri' => '/',
                'title' => 'Home',
                'status' => '1',
                'tagline' => '',
                'parent_id' => null,
                'link_type' => '',
                'category_id' => null,
                'active' => '',
                'category_name' => '',
                'url' => '/',
                'menu_id' => '2',
                'position' => null,
                'target' => '',
                'restricted_to' => '',
                'class' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '3',
                'slug' => '/',
                'uri' => '/',
                'title' => 'Flights',
                'status' => '1',
                'tagline' => '',
                'parent_id' => null,
                'link_type' => '',
                'category_id' => null,
                'active' => '',
                'category_name' => '',
                'url' => '/flights',
                'menu_id' => '1',
                'position' => null,
                'target' => '',
                'restricted_to' => '',
                'class' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '4',
                'slug' => '',
                'uri' => '/',
                'title' => 'Flights',
                'status' => '1',
                'tagline' => '',
                'parent_id' => null,
                'link_type' => '',
                'category_id' => null,
                'active' => '',
                'category_name' => '',
                'url' => '/flights',
                'menu_id' => '2',
                'position' => null,
                'target' => '',
                'restricted_to' => '',
                'class' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '5',
                'slug' => '/',
                'uri' => '/',
                'title' => 'Login',
                'status' => '1',
                'tagline' => '',
                'parent_id' => null,
                'link_type' => '',
                'category_id' => null,
                'active' => '',
                'category_name' => '',
                'url' => 'login',
                'menu_id' => '1',
                'position' => null,
                'target' => '',
                'restricted_to' => '',
                'class' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '6',
                'slug' => '/',
                'uri' => '/',
                'title' => 'Register',
                'status' => '1',
                'tagline' => '',
                'parent_id' => null,
                'link_type' => '',
                'category_id' => null,
                'active' => '',
                'category_name' => '',
                'url' => 'register',
                'menu_id' => '1',
                'position' => null,
                'target' => '',
                'restricted_to' => '',
                'class' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '7',
                'slug' => '/',
                'uri' => '/',
                'title' => 'About Us',
                'status' => '1',
                'tagline' => '',
                'parent_id' => null,
                'link_type' => '',
                'category_id' => null,
                'active' => '',
                'category_name' => '',
                'url' => 'about-us',
                'menu_id' => '3',
                'position' => null,
                'target' => '',
                'restricted_to' => '',
                'class' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '8',
                'slug' => '/',
                'uri' => '/',
                'title' => 'News & Updates',
                'status' => '1',
                'tagline' => '',
                'parent_id' => null,
                'link_type' => '',
                'category_id' => null,
                'active' => '',
                'category_name' => '',
                'url' => 'news-and-updates',
                'menu_id' => '3',
                'position' => null,
                'target' => '',
                'restricted_to' => '',
                'class' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '9',
                'slug' => '/',
                'uri' => '/',
                'title' => 'Private Policy',
                'status' => '1',
                'tagline' => '',
                'parent_id' => null,
                'link_type' => '',
                'category_id' => null,
                'active' => '',
                'category_name' => '',
                'url' => 'private-policy',
                'menu_id' => '3',
                'position' => null,
                'target' => '',
                'restricted_to' => '',
                'class' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '10',
                'slug' => '/',
                'uri' => '/',
                'title' => 'Terms & Conditions',
                'status' => '1',
                'tagline' => '',
                'parent_id' => null,
                'link_type' => '',
                'category_id' => null,
                'active' => '',
                'category_name' => '',
                'url' => 'terms-and-conditions',
                'menu_id' => '3',
                'position' => null,
                'target' => '',
                'restricted_to' => '',
                'class' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '11',
                'slug' => '/',
                'uri' => '/',
                'title' => 'Contact Us',
                'status' => '1',
                'tagline' => '',
                'parent_id' => null,
                'link_type' => '',
                'category_id' => null,
                'active' => '',
                'category_name' => '',
                'url' => 'contact-us',
                'menu_id' => '4',
                'position' => null,
                'target' => '',
                'restricted_to' => '',
                'class' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '12',
                'slug' => '/',
                'uri' => '/',
                'title' => 'How It Works',
                'status' => '1',
                'tagline' => '',
                'parent_id' => null,
                'link_type' => '',
                'category_id' => null,
                'active' => '',
                'category_name' => '',
                'url' => 'how-it-works',
                'menu_id' => '4',
                'position' => null,
                'target' => '',
                'restricted_to' => '',
                'class' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '13',
                'slug' => '/',
                'uri' => '/',
                'title' => 'FAQs',
                'status' => '1',
                'tagline' => '',
                'parent_id' => null,
                'link_type' => '',
                'category_id' => null,
                'active' => '',
                'category_name' => '',
                'url' => 'faqs',
                'menu_id' => '4',
                'position' => null,
                'target' => '',
                'restricted_to' => '',
                'class' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '14',
                'slug' => '/',
                'uri' => '/',
                'title' => 'Feedback',
                'status' => '1',
                'tagline' => '',
                'parent_id' => null,
                'link_type' => '',
                'category_id' => null,
                'active' => '',
                'category_name' => '',
                'url' => 'feedback',
                'menu_id' => '4',
                'position' => null,
                'target' => '',
                'restricted_to' => '',
                'class' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ]
        ];
        DB::table('menu_links')->insert( $menu_links );
    }

}