<?php namespace Modules\Pages\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use DB;

class PagesTableSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
    public function run()
    {
        DB::table('pages')->truncate();

        $pages = [
            [
                'id' => '1',
                'meta_robots_no_index' => '',
                'meta_robots_no_follow' => '',
                'is_home' => '1','css' => '',
                'js' => '',
                'template' => 'home',
                'slug' => '/',
                'uri' => '/',
                'title' => 'Home',
                'body' => '',
                'status' => '1',
                'meta_title' => '',
                'tagline' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'module' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '2',
                'meta_robots_no_index' => '',
                'meta_robots_no_follow' => '',
                'is_home' => '0','css' => '',
                'js' => '',
                'template' => 'login',
                'slug' => 'login',
                'uri' => 'login',
                'title' => 'Login',
                'body' => '',
                'status' => '1',
                'tagline' => '',
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'module' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '3',
                'meta_robots_no_index' => '',
                'meta_robots_no_follow' => '',
                'is_home' => '0','css' => '',
                'js' => '',
                'template' => 'register',
                'slug' => 'register',
                'uri' => 'register',
                'title' => 'Register',
                'body' => '',
                'status' => '1',
                'tagline' => '',
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'module' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '4',
                'meta_robots_no_index' => '',
                'meta_robots_no_follow' => '',
                'is_home' => '0','css' => '',
                'js' => '',
                'template' => 'default',
                'slug' => 'how-it-works',
                'uri' => 'how-it-works',
                'title' => 'How it works',
                'body' => '',
                'status' => '1',
                'tagline' => '',
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'module' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '5',
                'meta_robots_no_index' => '',
                'meta_robots_no_follow' => '',
                'is_home' => '0','css' => '',
                'js' => '',
                'template' => 'default',
                'slug' => 'private-policy',
                'uri' => 'private-policy',
                'title' => 'Private Policy',
                'body' => '',
                'status' => '1',
                'tagline' => '',
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'module' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '6',
                'meta_robots_no_index' => '',
                'meta_robots_no_follow' => '',
                'is_home' => '0','css' => '',
                'js' => '',
                'template' => 'default',
                'slug' => 'terms-and-conditions',
                'uri' => 'terms-and-conditions',
                'title' => 'Terms & Conditions',
                'body' => '',
                'status' => '1',
                'tagline' => '',
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'module' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '7',
                'meta_robots_no_index' => '',
                'meta_robots_no_follow' => '',
                'is_home' => '0','css' => '',
                'js' => '',
                'template' => 'default',
                'slug' => 'faqs',
                'uri' => 'faqs',
                'title' => 'FAQs',
                'body' => '',
                'status' => '1',
                'tagline' => '',
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'module' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '8',
                'meta_robots_no_index' => '',
                'meta_robots_no_follow' => '',
                'is_home' => '0','css' => '',
                'js' => '',
                'template' => 'default',
                'slug' => 'feedback',
                'uri' => 'feedback',
                'title' => 'Feedback',
                'body' => '',
                'status' => '1',
                'tagline' => '',
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'module' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '9',
                'meta_robots_no_index' => '',
                'meta_robots_no_follow' => '',
                'is_home' => '0','css' => '',
                'js' => '',
                'template' => 'default',
                'slug' => 'news-and-updates',
                'uri' => 'news-and-updates',
                'title' => 'News & Updates',
                'body' => '',
                'status' => '1',
                'tagline' => '',
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'module' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '10',
                'meta_robots_no_index' => '',
                'meta_robots_no_follow' => '',
                'is_home' => '0','css' => '',
                'js' => '',
                'template' => 'contact',
                'slug' => 'contact-us',
                'uri' => 'contact-us',
                'title' => 'Contact Us',
                'body' => '',
                'status' => '1',
                'tagline' => '',
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'module' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ],
            [
                'id' => '11',
                'meta_robots_no_index' => '',
                'meta_robots_no_follow' => '',
                'is_home' => '0','css' => '',
                'js' => '',
                'template' => 'default',
                'slug' => 'about-us',
                'uri' => 'about-us',
                'title' => 'About Us',
                'body' => '',
                'status' => '1',
                'tagline' => '',
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'module' => '',
                'created_at' => '2015-06-25 21:57:44',
                'updated_at' => '2015-06-25 20:26:35',
            ]

        ];
        DB::table('pages')->insert( $pages );
    }

}